/*
*   FileName:   ScribeDB_DataInsertion.sql
*   Author:     Scribe Dev Team
*   Purpose:    To create the needed stored procedures for the Scribe Database
*/

insert into Clients (ClientName, ClientAddress, ClientEmail, Contact_PhoneNumber, Description, Date_Aquired, Date_UnAquired, isDeleted) values ('Voomm', '593 Northwestern Center', 'irowcliffe0@163.com', '(616) 3468490', 'Business Development', '2021-12-05', '2023-07-21', 0);
insert into Clients (ClientName, ClientAddress, ClientEmail, Contact_PhoneNumber, Description, Date_Aquired, Date_UnAquired, isDeleted) values ('Riffpath', '63 Laurel Hill', 'amuschette1@phoca.cz', '(321) 5556778', 'Support', '2022-03-21', '2022-07-23', 0);
insert into Clients (ClientName, ClientAddress, ClientEmail, Contact_PhoneNumber, Description, Date_Aquired, Date_UnAquired, isDeleted) values ('Topiclounge', '68 Bartillon Plaza', 'ahabergham2@biblegateway.com', '(818) 6726189', 'Human Resources', '2023-12-13', '2022-02-22', 0);
insert into Clients (ClientName, ClientAddress, ClientEmail, Contact_PhoneNumber, Description, Date_Aquired, Date_UnAquired, isDeleted) values ('Jazzy', '06202 Jackson Park', 'cmaryott3@paginegialle.it', '(374) 1842143', 'Services', '2022-08-17', '2023-08-27', 0);
insert into Clients (ClientName, ClientAddress, ClientEmail, Contact_PhoneNumber, Description, Date_Aquired, Date_UnAquired, isDeleted) values ('Mynte', '758 Vera Circle', 'wcleiment4@nps.gov', '(260) 7142834', 'Sales', '2022-05-12', '2022-10-10', 1);
insert into Clients (ClientName, ClientAddress, ClientEmail, Contact_PhoneNumber, Description, Date_Aquired, Date_UnAquired, isDeleted) values ('Bubbletube', '27 Luster Pass', 'mtuvey5@woothemes.com', '(454) 6738502', 'Research and Development', '2022-01-19', '2022-04-05', 0);
insert into Clients (ClientName, ClientAddress, ClientEmail, Contact_PhoneNumber, Description, Date_Aquired, Date_UnAquired, isDeleted) values ('Zoombeat', '49164 Hanover Crossing', 'dfragino6@nature.com', '(858) 3359951', 'Training', '2022-01-28', '2023-01-01', 1);
insert into Clients (ClientName, ClientAddress, ClientEmail, Contact_PhoneNumber, Description, Date_Aquired, Date_UnAquired, isDeleted) values ('Twinder', '4 Steensland Park', 'cbarczynski7@ihg.com', '(954) 8296344', 'Marketing', '2021-12-09', '2023-11-23', 0);
insert into Clients (ClientName, ClientAddress, ClientEmail, Contact_PhoneNumber, Description, Date_Aquired, Date_UnAquired, isDeleted) values ('Eadel', '68 3rd Place', 'vreubens8@wiley.com', '(219) 5689448', 'Legal', '2022-12-28', '2023-08-16', 1);
insert into Clients (ClientName, ClientAddress, ClientEmail, Contact_PhoneNumber, Description, Date_Aquired, Date_UnAquired, isDeleted) values ('Meemm', '17729 Basil Way', 'mmulvey9@google.fr', '(298) 8352465', 'Accounting', '2021-12-14', '2022-04-05', 0);
insert into Clients (ClientName, ClientAddress, ClientEmail, Contact_PhoneNumber, Description, Date_Aquired, Date_UnAquired, isDeleted) values ('Wikibox', '5 Stoughton Pass', 'itillmana@t.co', '(225) 2590996', 'Legal', '2023-02-23', '2021-12-15', 0);
insert into Clients (ClientName, ClientAddress, ClientEmail, Contact_PhoneNumber, Description, Date_Aquired, Date_UnAquired, isDeleted) values ('Brightbean', '7039 Grim Junction', 'rbrackenburyb@ibm.com', '(688) 5226696', 'Product Management', '2022-06-17', '2022-04-09', 0);
insert into Clients (ClientName, ClientAddress, ClientEmail, Contact_PhoneNumber, Description, Date_Aquired, Date_UnAquired, isDeleted) values ('Yamia', '5368 Grayhawk Road', 'spartlettc@dailymail.co.uk', '(783) 4340767', 'Legal', '2022-02-12', '2022-12-16', 0);
insert into Clients (ClientName, ClientAddress, ClientEmail, Contact_PhoneNumber, Description, Date_Aquired, Date_UnAquired, isDeleted) values ('Wikido', '88 Cardinal Avenue', 'mclendinningd@networkadvertising.org', '(169) 8139770', 'Marketing', '2022-09-07', '2023-01-19', 1);
insert into Clients (ClientName, ClientAddress, ClientEmail, Contact_PhoneNumber, Description, Date_Aquired, Date_UnAquired, isDeleted) values ('Zoombeat', '5478 Buell Park', 'vlefleye@unicef.org', '(990) 6010857', 'Product Management', '2023-02-20', '2023-01-08', 0);
insert into Clients (ClientName, ClientAddress, ClientEmail, Contact_PhoneNumber, Description, Date_Aquired, Date_UnAquired, isDeleted) values ('Jamia', '25 Huxley Road', 'schidlowf@ed.gov', '(204) 5569059', 'Engineering', '2022-11-08', '2022-03-25', 1);
insert into Clients (ClientName, ClientAddress, ClientEmail, Contact_PhoneNumber, Description, Date_Aquired, Date_UnAquired, isDeleted) values ('Gigaclub', '77 New Castle Point', 'whairsg@wikispaces.com', '(174) 2174103', 'Product Management', '2023-02-27', '2022-06-13', 1);
insert into Clients (ClientName, ClientAddress, ClientEmail, Contact_PhoneNumber, Description, Date_Aquired, Date_UnAquired, isDeleted) values ('Shufflester', '7 Gale Alley', 'ajusticeh@earthlink.net', '(616) 2675249', 'Sales', '2023-10-23', '2024-01-22', 1);
insert into Clients (ClientName, ClientAddress, ClientEmail, Contact_PhoneNumber, Description, Date_Aquired, Date_UnAquired, isDeleted) values ('Yodo', '83 Stuart Park', 'brouzeti@squidoo.com', '(806) 8071401', 'Accounting', '2023-01-12', '2023-11-26', 1);
insert into Clients (ClientName, ClientAddress, ClientEmail, Contact_PhoneNumber, Description, Date_Aquired, Date_UnAquired, isDeleted) values ('Plambee', '78 Barnett Hill', 'kinglesj@360.cn', '(869) 1359584', 'Business Development', '2022-06-06', '2023-09-11', 1);

insert into Positions (Description, BaseRate, isDeleted) values ('Training', 9899, 0);
insert into Positions (Description, BaseRate, isDeleted) values ('Business Development', 2896, 1);
insert into Positions (Description, BaseRate, isDeleted) values ('Human Resources', 2553, 0);
insert into Positions (Description, BaseRate, isDeleted) values ('Support', 3822, 0);
insert into Positions (Description, BaseRate, isDeleted) values ('Product Management', 4538, 0);
insert into Positions (Description, BaseRate, isDeleted) values ('Support', 4690, 1);
insert into Positions (Description, BaseRate, isDeleted) values ('Research and Development', 9295, 1);
insert into Positions (Description, BaseRate, isDeleted) values ('Business Development', 8130, 0);
insert into Positions (Description, BaseRate, isDeleted) values ('Training', 4057, 0);
insert into Positions (Description, BaseRate, isDeleted) values ('Support', 3768, 0);
insert into Positions (Description, BaseRate, isDeleted) values ('Research and Development', 2984, 0);
insert into Positions (Description, BaseRate, isDeleted) values ('Support', 5683, 1);
insert into Positions (Description, BaseRate, isDeleted) values ('Engineering', 8672, 1);
insert into Positions (Description, BaseRate, isDeleted) values ('Business Development', 1154, 0);
insert into Positions (Description, BaseRate, isDeleted) values ('Research and Development', 6376, 0);
insert into Positions (Description, BaseRate, isDeleted) values ('Training', 8924, 1);
insert into Positions (Description, BaseRate, isDeleted) values ('Marketing', 7993, 1);
insert into Positions (Description, BaseRate, isDeleted) values ('Research and Development', 7751, 1);
insert into Positions (Description, BaseRate, isDeleted) values ('Accounting', 5379, 1);
insert into Positions (Description, BaseRate, isDeleted) values ('Business Development', 5232, 0);

insert into HAEmployees (Employee_FirstName, Employee_LastName, PositionID, Employee_Email, Employee_PhoneNumber, isDeleted) values ('Sloane', 'Crutcher', 5, 'scrutcher0@ox.ac.uk', '(787) 7068257', 1);
insert into HAEmployees (Employee_FirstName, Employee_LastName, PositionID, Employee_Email, Employee_PhoneNumber, isDeleted) values ('Katheryn', 'Jurewicz', 7, 'kjurewicz1@reference.com', '(841) 7496880', 0);
insert into HAEmployees (Employee_FirstName, Employee_LastName, PositionID, Employee_Email, Employee_PhoneNumber, isDeleted) values ('Cullen', 'Gatecliff', 18, 'cgatecliff2@unblog.fr', '(579) 4413041', 1);
insert into HAEmployees (Employee_FirstName, Employee_LastName, PositionID, Employee_Email, Employee_PhoneNumber, isDeleted) values ('Willow', 'Bellord', 6, 'wbellord3@skype.com', '(520) 2609064', 1);
insert into HAEmployees (Employee_FirstName, Employee_LastName, PositionID, Employee_Email, Employee_PhoneNumber, isDeleted) values ('Aubree', 'Shakespear', 15, 'ashakespear4@economist.com', '(155) 1939926', 1);
insert into HAEmployees (Employee_FirstName, Employee_LastName, PositionID, Employee_Email, Employee_PhoneNumber, isDeleted) values ('Karlen', 'Tilt', 11, 'ktilt5@state.tx.us', '(749) 9897848', 0);
insert into HAEmployees (Employee_FirstName, Employee_LastName, PositionID, Employee_Email, Employee_PhoneNumber, isDeleted) values ('Cati', 'Stannas', 7, 'cstannas6@wikia.com', '(283) 7545640', 0);
insert into HAEmployees (Employee_FirstName, Employee_LastName, PositionID, Employee_Email, Employee_PhoneNumber, isDeleted) values ('Cathryn', 'Arderne', 17, 'carderne7@wikispaces.com', '(780) 4986127', 1);
insert into HAEmployees (Employee_FirstName, Employee_LastName, PositionID, Employee_Email, Employee_PhoneNumber, isDeleted) values ('Constancy', 'Ockwell', 1, 'cockwell8@oakley.com', '(310) 7466959', 0);
insert into HAEmployees (Employee_FirstName, Employee_LastName, PositionID, Employee_Email, Employee_PhoneNumber, isDeleted) values ('Town', 'Hurle', 2, 'thurle9@businessweek.com', '(445) 2994563', 0);
insert into HAEmployees (Employee_FirstName, Employee_LastName, PositionID, Employee_Email, Employee_PhoneNumber, isDeleted) values ('Dalia', 'Guilleton', 12, 'dguilletona@tiny.cc', '(103) 8453305', 0);
insert into HAEmployees (Employee_FirstName, Employee_LastName, PositionID, Employee_Email, Employee_PhoneNumber, isDeleted) values ('Cori', 'O''Fearguise', 8, 'cofearguiseb@noaa.gov', '(444) 3822723', 1);
insert into HAEmployees (Employee_FirstName, Employee_LastName, PositionID, Employee_Email, Employee_PhoneNumber, isDeleted) values ('Wilburt', 'Beeck', 16, 'wbeeckc@businessweek.com', '(535) 7598100', 0);
insert into HAEmployees (Employee_FirstName, Employee_LastName, PositionID, Employee_Email, Employee_PhoneNumber, isDeleted) values ('Melany', 'Gerrels', 2, 'mgerrelsd@latimes.com', '(200) 2912753', 1);
insert into HAEmployees (Employee_FirstName, Employee_LastName, PositionID, Employee_Email, Employee_PhoneNumber, isDeleted) values ('Cirstoforo', 'Castanos', 20, 'ccastanose@noaa.gov', '(273) 1731331', 0);
insert into HAEmployees (Employee_FirstName, Employee_LastName, PositionID, Employee_Email, Employee_PhoneNumber, isDeleted) values ('Frederico', 'Pamphilon', 6, 'fpamphilonf@squidoo.com', '(642) 6508434', 0);
insert into HAEmployees (Employee_FirstName, Employee_LastName, PositionID, Employee_Email, Employee_PhoneNumber, isDeleted) values ('Pamelina', 'McEvon', 1, 'pmcevong@biglobe.ne.jp', '(116) 4709270', 0);
insert into HAEmployees (Employee_FirstName, Employee_LastName, PositionID, Employee_Email, Employee_PhoneNumber, isDeleted) values ('Maribel', 'Fiennes', 14, 'mfiennesh@slideshare.net', '(963) 8339288', 1);
insert into HAEmployees (Employee_FirstName, Employee_LastName, PositionID, Employee_Email, Employee_PhoneNumber, isDeleted) values ('Kalindi', 'Mynard', 6, 'kmynardi@go.com', '(680) 2024700', 0);
insert into HAEmployees (Employee_FirstName, Employee_LastName, PositionID, Employee_Email, Employee_PhoneNumber, isDeleted) values ('Leonid', 'Roxbrough', 9, 'lroxbroughj@bloomberg.com', '(305) 5262984', 1);

insert into Users (Username, Password, FirstName, LastName, userType, HAEmployeeID, isDeleted) values ('sbuckler0', 'NRO0YT77Q5uT', 'Skyler', 'Buckler', 'Koala', 3, 1);
insert into Users (Username, Password, FirstName, LastName, userType, HAEmployeeID, isDeleted) values ('gleyninye1', 'mo9l8jkHLK', 'Granthem', 'Leyninye', 'Dragon, frilled', 8, 1);
insert into Users (Username, Password, FirstName, LastName, userType, HAEmployeeID, isDeleted) values ('pgilffillan2', 'T6OoQUg12FGK', 'Phillida', 'Gilffillan', 'Small-clawed otter', 1, 0);
insert into Users (Username, Password, FirstName, LastName, userType, HAEmployeeID, isDeleted) values ('wgreedy3', 'hHml44vk', 'Wren', 'Greedy', 'Roe deer', 8, 0);
insert into Users (Username, Password, FirstName, LastName, userType, HAEmployeeID, isDeleted) values ('cvinden4', 'f6QVXaS', 'Curr', 'Vinden', 'Eagle, long-crested hawk', 16, 0);
insert into Users (Username, Password, FirstName, LastName, userType, HAEmployeeID, isDeleted) values ('dportam5', 'a6v0DAl1jv9V', 'Dodi', 'Portam', 'American Virginia opossum', 10, 1);
insert into Users (Username, Password, FirstName, LastName, userType, HAEmployeeID, isDeleted) values ('lgrinnov6', 'MF9hwHUJ', 'Lyn', 'Grinnov', 'Penguin, fairy', 12, 0);
insert into Users (Username, Password, FirstName, LastName, userType, HAEmployeeID, isDeleted) values ('rkime7', 'OUmfF9NuIhgq', 'Robbi', 'Kime', 'Cape clawless otter', 4, 0);
insert into Users (Username, Password, FirstName, LastName, userType, HAEmployeeID, isDeleted) values ('jparnell8', 'a1jtGpXaD', 'Jyoti', 'Parnell', 'Sparrow, house', 5, 0);
insert into Users (Username, Password, FirstName, LastName, userType, HAEmployeeID, isDeleted) values ('olowdwell9', 'aO4MjwZ', 'Olia', 'Lowdwell', 'Frilled dragon', 15, 0);
insert into Users (Username, Password, FirstName, LastName, userType, HAEmployeeID, isDeleted) values ('mcrasforda', 'rxTviLK', 'Marina', 'Crasford', 'Goanna lizard', 1, 1);
insert into Users (Username, Password, FirstName, LastName, userType, HAEmployeeID, isDeleted) values ('gcattob', 'nDFkIPWT33', 'Gloriane', 'Catto', 'Wagtail, african pied', 7, 1);
insert into Users (Username, Password, FirstName, LastName, userType, HAEmployeeID, isDeleted) values ('kflockhartc', 'bDa3A7', 'Kingston', 'Flockhart', 'Chameleon (unidentified)', 19, 0);
insert into Users (Username, Password, FirstName, LastName, userType, HAEmployeeID, isDeleted) values ('mcouroyd', 'bA9JHH2xpwDr', 'Maryrose', 'Couroy', 'Swan, trumpeter', 2, 0);
insert into Users (Username, Password, FirstName, LastName, userType, HAEmployeeID, isDeleted) values ('pquinceye', 'Iow9D9HLmCcv', 'Penni', 'Quincey', 'Mynah, indian', 2, 0);
insert into Users (Username, Password, FirstName, LastName, userType, HAEmployeeID, isDeleted) values ('mduffieldf', 'kwGxueHdy', 'Monique', 'Duffield', 'Cattle egret', 3, 1);
insert into Users (Username, Password, FirstName, LastName, userType, HAEmployeeID, isDeleted) values ('dsaggg', 'Dte8Ft1NOa', 'Darryl', 'Sagg', 'Heron, green-backed', 20, 0);
insert into Users (Username, Password, FirstName, LastName, userType, HAEmployeeID, isDeleted) values ('npibsworthh', 'trJsLz', 'Nadya', 'Pibsworth', 'Deer, mule', 2, 0);
insert into Users (Username, Password, FirstName, LastName, userType, HAEmployeeID, isDeleted) values ('nwolferi', 'mIIHjtD0c', 'Nerissa', 'Wolfer', 'Blue duck', 13, 0);
insert into Users (Username, Password, FirstName, LastName, userType, HAEmployeeID, isDeleted) values ('ldefondj', 'o6sreFBlA', 'Linda', 'Defond', 'Jaguar', 6, 1);

insert into AssignedEmployees (HAEmployeeID, ClientID, PreviousAssignment, DateAssigned, isDeleted) values (15, 15, 9, '2022-07-22', 0);
insert into AssignedEmployees (HAEmployeeID, ClientID, PreviousAssignment, DateAssigned, isDeleted) values (7, 11, 1, '2022-06-17', 0);
insert into AssignedEmployees (HAEmployeeID, ClientID, PreviousAssignment, DateAssigned, isDeleted) values (15, 1, 8, '2022-02-16', 0);
insert into AssignedEmployees (HAEmployeeID, ClientID, PreviousAssignment, DateAssigned, isDeleted) values (19, 17, 16, '2022-08-03', 0);
insert into AssignedEmployees (HAEmployeeID, ClientID, PreviousAssignment, DateAssigned, isDeleted) values (18, 6, 19, '2022-10-30', 1);
insert into AssignedEmployees (HAEmployeeID, ClientID, PreviousAssignment, DateAssigned, isDeleted) values (16, 15, 15, '2022-10-05', 0);
insert into AssignedEmployees (HAEmployeeID, ClientID, PreviousAssignment, DateAssigned, isDeleted) values (20, 10, 11, '2022-04-11', 1);
insert into AssignedEmployees (HAEmployeeID, ClientID, PreviousAssignment, DateAssigned, isDeleted) values (17, 2, 3, '2021-12-12', 1);
insert into AssignedEmployees (HAEmployeeID, ClientID, PreviousAssignment, DateAssigned, isDeleted) values (16, 3, 2, '2022-05-23', 0);
insert into AssignedEmployees (HAEmployeeID, ClientID, PreviousAssignment, DateAssigned, isDeleted) values (20, 6, 13, '2022-05-07', 1);
insert into AssignedEmployees (HAEmployeeID, ClientID, PreviousAssignment, DateAssigned, isDeleted) values (3, 5, 2, '2022-09-30', 0);
insert into AssignedEmployees (HAEmployeeID, ClientID, PreviousAssignment, DateAssigned, isDeleted) values (8, 20, 4, '2022-08-02', 1);
insert into AssignedEmployees (HAEmployeeID, ClientID, PreviousAssignment, DateAssigned, isDeleted) values (18, 15, 5, '2022-05-27', 1);
insert into AssignedEmployees (HAEmployeeID, ClientID, PreviousAssignment, DateAssigned, isDeleted) values (18, 1, 13, '2022-07-31', 0);
insert into AssignedEmployees (HAEmployeeID, ClientID, PreviousAssignment, DateAssigned, isDeleted) values (1, 16, 17, '2022-01-02', 0);
insert into AssignedEmployees (HAEmployeeID, ClientID, PreviousAssignment, DateAssigned, isDeleted) values (12, 10, 19, '2022-07-14', 1);
insert into AssignedEmployees (HAEmployeeID, ClientID, PreviousAssignment, DateAssigned, isDeleted) values (13, 12, 1, '2022-01-02', 1);
insert into AssignedEmployees (HAEmployeeID, ClientID, PreviousAssignment, DateAssigned, isDeleted) values (6, 12, 6, '2022-03-09', 0);
insert into AssignedEmployees (HAEmployeeID, ClientID, PreviousAssignment, DateAssigned, isDeleted) values (2, 5, 10, '2022-08-30', 0);
insert into AssignedEmployees (HAEmployeeID, ClientID, PreviousAssignment, DateAssigned, isDeleted) values (10, 9, 9, '2022-07-23', 0);

insert into Banks (BankName, Bank_PhoneNumber, isDeleted) values ('Chase', '(729) 5468657', 0);
insert into Banks (BankName, Bank_PhoneNumber, isDeleted) values ('Huntington', '(571) 5604829', 0);
insert into Banks (BankName, Bank_PhoneNumber, isDeleted) values ('Silicon Valley Bank', '(796) 2372905', 1);
insert into Banks (BankName, Bank_PhoneNumber, isDeleted) values ('Key', '(149) 6584139', 1);
insert into Banks (BankName, Bank_PhoneNumber, isDeleted) values ('Satender', '(798) 4639489', 1);

insert into BankAccounts (ClientID, BankID, AccountType, AccountNumber, lastReconBalance, lastReconDate, isDeleted) values (1, 3, 'Voltsillam', 96537534, 14504.72, '2022-06-22', 0);
insert into BankAccounts (ClientID, BankID, AccountType, AccountNumber, lastReconBalance, lastReconDate, isDeleted) values (7, 3, 'Daltfresh', 19305095, 577244.25, '2021-12-28', 0);
insert into BankAccounts (ClientID, BankID, AccountType, AccountNumber, lastReconBalance, lastReconDate, isDeleted) values (16, 4, 'Y-find', 95313148, 777777.9, '2022-12-15', 0);
insert into BankAccounts (ClientID, BankID, AccountType, AccountNumber, lastReconBalance, lastReconDate, isDeleted) values (9, 4, 'Vagram', 71956218, 559692.88, '2022-11-05', 1);
insert into BankAccounts (ClientID, BankID, AccountType, AccountNumber, lastReconBalance, lastReconDate, isDeleted) values (12, 1, 'Fix San', 20592300, 449998.99, '2022-10-21', 1);
insert into BankAccounts (ClientID, BankID, AccountType, AccountNumber, lastReconBalance, lastReconDate, isDeleted) values (15, 1, 'Pannier', 27339824, 276078.11, '2022-05-23', 0);
insert into BankAccounts (ClientID, BankID, AccountType, AccountNumber, lastReconBalance, lastReconDate, isDeleted) values (15, 3, 'Fintone', 42704427, 400975.08, '2022-10-07', 1);
insert into BankAccounts (ClientID, BankID, AccountType, AccountNumber, lastReconBalance, lastReconDate, isDeleted) values (11, 2, 'Wrapsafe', 17753698, 464789.78, '2023-02-07', 0);
insert into BankAccounts (ClientID, BankID, AccountType, AccountNumber, lastReconBalance, lastReconDate, isDeleted) values (19, 4, 'Latlux', 17722978, 376304.49, '2021-10-24', 1);
insert into BankAccounts (ClientID, BankID, AccountType, AccountNumber, lastReconBalance, lastReconDate, isDeleted) values (10, 3, 'Bitchip', 97923822, 753826.05, '2022-08-13', 1);
insert into BankAccounts (ClientID, BankID, AccountType, AccountNumber, lastReconBalance, lastReconDate, isDeleted) values (1, 1, 'Viva', 81130394, 640445.43, '2022-01-21', 1);
insert into BankAccounts (ClientID, BankID, AccountType, AccountNumber, lastReconBalance, lastReconDate, isDeleted) values (3, 2, 'Sonsing', 56058761, 961192.6, '2022-08-20', 0);
insert into BankAccounts (ClientID, BankID, AccountType, AccountNumber, lastReconBalance, lastReconDate, isDeleted) values (17, 5, 'Alphazap', 29359577, 698098.0, '2022-06-27', 1);
insert into BankAccounts (ClientID, BankID, AccountType, AccountNumber, lastReconBalance, lastReconDate, isDeleted) values (19, 2, 'Quo Lux', 53574638, 349508.08, '2021-09-08', 1);
insert into BankAccounts (ClientID, BankID, AccountType, AccountNumber, lastReconBalance, lastReconDate, isDeleted) values (10, 3, 'Daltfresh', 42695700, 21375.19, '2022-09-25', 0);
insert into BankAccounts (ClientID, BankID, AccountType, AccountNumber, lastReconBalance, lastReconDate, isDeleted) values (10, 1, 'Span', 53555926, 960608.74, '2022-10-14', 1);
insert into BankAccounts (ClientID, BankID, AccountType, AccountNumber, lastReconBalance, lastReconDate, isDeleted) values (14, 2, 'Sonsing', 14051862, 47655.82, '2021-08-30', 1);
insert into BankAccounts (ClientID, BankID, AccountType, AccountNumber, lastReconBalance, lastReconDate, isDeleted) values (8, 4, 'Duobam', 31136544, 917306.39, '2021-09-19', 1);
insert into BankAccounts (ClientID, BankID, AccountType, AccountNumber, lastReconBalance, lastReconDate, isDeleted) values (3, 4, 'Alphazap', 52290515, 947770.65, '2022-12-28', 0);
insert into BankAccounts (ClientID, BankID, AccountType, AccountNumber, lastReconBalance, lastReconDate, isDeleted) values (13, 4, 'Zaam-Dox', 50429285, 661052.8, '2022-07-20', 1);

insert into TransactionTypes (Description, isCredit, isDeleted) values ('Crimson', 0, 1);
insert into TransactionTypes (Description, isCredit, isDeleted) values ('Green', 1, 1);
insert into TransactionTypes (Description, isCredit, isDeleted) values ('Puce', 1, 1);
insert into TransactionTypes (Description, isCredit, isDeleted) values ('Orange', 0, 0);
insert into TransactionTypes (Description, isCredit, isDeleted) values ('Orange', 1, 0);
insert into TransactionTypes (Description, isCredit, isDeleted) values ('Purple', 0, 1);
insert into TransactionTypes (Description, isCredit, isDeleted) values ('Maroon', 0, 1);
insert into TransactionTypes (Description, isCredit, isDeleted) values ('Pink', 0, 0);
insert into TransactionTypes (Description, isCredit, isDeleted) values ('Indigo', 0, 1);
insert into TransactionTypes (Description, isCredit, isDeleted) values ('Goldenrod', 0, 1);
insert into TransactionTypes (Description, isCredit, isDeleted) values ('Crimson', 1, 1);
insert into TransactionTypes (Description, isCredit, isDeleted) values ('Puce', 0, 0);
insert into TransactionTypes (Description, isCredit, isDeleted) values ('Green', 1, 0);
insert into TransactionTypes (Description, isCredit, isDeleted) values ('Puce', 1, 1);
insert into TransactionTypes (Description, isCredit, isDeleted) values ('Fuscia', 1, 0);
insert into TransactionTypes (Description, isCredit, isDeleted) values ('Red', 0, 1);
insert into TransactionTypes (Description, isCredit, isDeleted) values ('Khaki', 1, 1);
insert into TransactionTypes (Description, isCredit, isDeleted) values ('Blue', 0, 0);
insert into TransactionTypes (Description, isCredit, isDeleted) values ('Yellow', 0, 0);
insert into TransactionTypes (Description, isCredit, isDeleted) values ('Purple', 1, 1);

insert into AccountTypes (AccountTypeName, Description, isMain, isDeleted) values ('Income', 'MainAccount', 1, 0);
insert into AccountTypes (AccountTypeName, Description, isMain, isDeleted) values ('Expenses', 'MainAccount', 1, 0);
insert into AccountTypes (AccountTypeName, Description, isMain, isDeleted) values ('Liabilities', 'MainAccount', 1, 0);
insert into AccountTypes (AccountTypeName, Description, isMain, isDeleted) values ('Assets', 'MainAccount', 1, 0);
insert into AccountTypes (AccountTypeName, Description, isMain, isDeleted) values ('Equity', 'MainAccount', 1, 0);

insert into Transactions (BankAccountID, Date_Made, Date_Processed, Amount, Description, TransNum, TransactionTypeID, AccountTypeID, isReconciled, isDeleted) values (20, '2022-02-06', '2020-11-26', 3261.1, 'Bugeranus caruncalatus', 80, 5, 1, 1, 0);
insert into Transactions (BankAccountID, Date_Made, Date_Processed, Amount, Description, TransNum, TransactionTypeID, AccountTypeID, isReconciled, isDeleted) values (17, '2023-03-10', '2021-11-12', 13794.81, 'Rangifer tarandus', 56, 18, 3, 0, 0);
insert into Transactions (BankAccountID, Date_Made, Date_Processed, Amount, Description, TransNum, TransactionTypeID, AccountTypeID, isReconciled, isDeleted) values (14, '2022-05-11', '2022-08-20', 13974.29, 'Gyps fulvus', 65, 14, 4, 1, 0);
insert into Transactions (BankAccountID, Date_Made, Date_Processed, Amount, Description, TransNum, TransactionTypeID, AccountTypeID, isReconciled, isDeleted) values (13, '2021-09-19', '2022-05-03', 18407.13, 'Crotaphytus collaris', 88, 17, 4, 0, 1);
insert into Transactions (BankAccountID, Date_Made, Date_Processed, Amount, Description, TransNum, TransactionTypeID, AccountTypeID, isReconciled, isDeleted) values (12, '2021-07-09', '2023-01-21', 8377.37, 'Cacatua tenuirostris', 55, 14, 3, 0, 0);
insert into Transactions (BankAccountID, Date_Made, Date_Processed, Amount, Description, TransNum, TransactionTypeID, AccountTypeID, isReconciled, isDeleted) values (8, '2023-01-11', '2021-04-07', 15988.92, 'Bettongia penicillata', 58, 8, 3, 0, 1);
insert into Transactions (BankAccountID, Date_Made, Date_Processed, Amount, Description, TransNum, TransactionTypeID, AccountTypeID, isReconciled, isDeleted) values (7, '2022-02-09', '2021-11-10', 4819.32, 'Numida meleagris', 64, 7, 1, 1, 1);
insert into Transactions (BankAccountID, Date_Made, Date_Processed, Amount, Description, TransNum, TransactionTypeID, AccountTypeID, isReconciled, isDeleted) values (6, '2022-05-18', '2022-06-10', 7472.4, 'Sarkidornis melanotos', 55, 8, 5, 1, 1);
insert into Transactions (BankAccountID, Date_Made, Date_Processed, Amount, Description, TransNum, TransactionTypeID, AccountTypeID, isReconciled, isDeleted) values (18, '2022-08-24', '2022-09-22', 3018.45, 'Ephippiorhynchus mycteria', 69, 3, 3, 0, 0);
insert into Transactions (BankAccountID, Date_Made, Date_Processed, Amount, Description, TransNum, TransactionTypeID, AccountTypeID, isReconciled, isDeleted) values (1, '2022-01-10', '2022-06-25', 9664.81, 'Bos taurus', 94, 15, 1, 1, 0);
insert into Transactions (BankAccountID, Date_Made, Date_Processed, Amount, Description, TransNum, TransactionTypeID, AccountTypeID, isReconciled, isDeleted) values (7, '2021-04-30', '2022-02-21', 16981.85, 'Iguana iguana', 84, 7, 3, 1, 0);
insert into Transactions (BankAccountID, Date_Made, Date_Processed, Amount, Description, TransNum, TransactionTypeID, AccountTypeID, isReconciled, isDeleted) values (11, '2023-02-27', '2023-01-12', 12307.1, 'Speotyte cuniculata', 52, 3, 2, 0, 0);
insert into Transactions (BankAccountID, Date_Made, Date_Processed, Amount, Description, TransNum, TransactionTypeID, AccountTypeID, isReconciled, isDeleted) values (7, '2021-04-23', '2021-04-05', 5053.09, 'Dasyurus maculatus', 92, 10, 1, 0, 1);
insert into Transactions (BankAccountID, Date_Made, Date_Processed, Amount, Description, TransNum, TransactionTypeID, AccountTypeID, isReconciled, isDeleted) values (2, '2022-11-23', '2021-03-15', 16625.58, 'Bucorvus leadbeateri', 73, 10, 5, 0, 0);
insert into Transactions (BankAccountID, Date_Made, Date_Processed, Amount, Description, TransNum, TransactionTypeID, AccountTypeID, isReconciled, isDeleted) values (4, '2022-12-20', '2022-11-19', 2003.47, 'Smithopsis crassicaudata', 61, 9, 1, 0, 1);
insert into Transactions (BankAccountID, Date_Made, Date_Processed, Amount, Description, TransNum, TransactionTypeID, AccountTypeID, isReconciled, isDeleted) values (12, '2022-07-23', '2022-06-30', 5293.22, 'Sula nebouxii', 59, 4, 3, 1, 1);
insert into Transactions (BankAccountID, Date_Made, Date_Processed, Amount, Description, TransNum, TransactionTypeID, AccountTypeID, isReconciled, isDeleted) values (18, '2021-04-18', '2021-03-14', 5780.86, 'Macaca radiata', 90, 1, 4, 0, 0);
insert into Transactions (BankAccountID, Date_Made, Date_Processed, Amount, Description, TransNum, TransactionTypeID, AccountTypeID, isReconciled, isDeleted) values (12, '2021-09-23', '2022-07-03', 15264.46, 'Coluber constrictor', 78, 10, 2, 1, 1);
insert into Transactions (BankAccountID, Date_Made, Date_Processed, Amount, Description, TransNum, TransactionTypeID, AccountTypeID, isReconciled, isDeleted) values (15, '2021-09-03', '2022-09-21', 2977.1, 'Gorilla gorilla', 62, 12, 5, 1, 1);
insert into Transactions (BankAccountID, Date_Made, Date_Processed, Amount, Description, TransNum, TransactionTypeID, AccountTypeID, isReconciled, isDeleted) values (6, '2022-06-23', '2022-02-07', 18012.09, 'Boa constrictor mexicana', 93, 19, 4, 1, 0);

insert into ClientAccounts (ClientID, AccountTypeID, Balance, isDeleted) values (11, 4, 742704.72, 1);
insert into ClientAccounts (ClientID, AccountTypeID, Balance, isDeleted) values (3, 4, 561724.9, 0);
insert into ClientAccounts (ClientID, AccountTypeID, Balance, isDeleted) values (13, 5, 662196.0, 1);
insert into ClientAccounts (ClientID, AccountTypeID, Balance, isDeleted) values (6, 2, 752313.7, 0);
insert into ClientAccounts (ClientID, AccountTypeID, Balance, isDeleted) values (19, 3, 873977.77, 0);
insert into ClientAccounts (ClientID, AccountTypeID, Balance, isDeleted) values (8, 2, 443017.24, 0);
insert into ClientAccounts (ClientID, AccountTypeID, Balance, isDeleted) values (6, 4, 40928.88, 1);
insert into ClientAccounts (ClientID, AccountTypeID, Balance, isDeleted) values (4, 5, 815279.4, 0);
insert into ClientAccounts (ClientID, AccountTypeID, Balance, isDeleted) values (3, 3, 779733.87, 1);
insert into ClientAccounts (ClientID, AccountTypeID, Balance, isDeleted) values (4, 3, 62080.96, 0);
insert into ClientAccounts (ClientID, AccountTypeID, Balance, isDeleted) values (9, 5, 85471.98, 0);
insert into ClientAccounts (ClientID, AccountTypeID, Balance, isDeleted) values (2, 4, 735193.09, 0);
insert into ClientAccounts (ClientID, AccountTypeID, Balance, isDeleted) values (19, 1, 782032.85, 1);
insert into ClientAccounts (ClientID, AccountTypeID, Balance, isDeleted) values (7, 3, 285766.37, 1);
insert into ClientAccounts (ClientID, AccountTypeID, Balance, isDeleted) values (2, 4, 16114.3, 1);
insert into ClientAccounts (ClientID, AccountTypeID, Balance, isDeleted) values (17, 3, 507677.15, 0);
insert into ClientAccounts (ClientID, AccountTypeID, Balance, isDeleted) values (14, 2, 319214.86, 0);
insert into ClientAccounts (ClientID, AccountTypeID, Balance, isDeleted) values (1, 2, 790373.0, 0);
insert into ClientAccounts (ClientID, AccountTypeID, Balance, isDeleted) values (11, 4, 197504.46, 0);
insert into ClientAccounts (ClientID, AccountTypeID, Balance, isDeleted) values (4, 1, 459429.93, 1);
