/*
*   FileName:   ScribeDB_DataInsertion.sql
*   Author:     Scribe Dev Team
*   Purpose:    To create the needed stored procedures for the Scribe Database
*/

insert into Clients (ClientName, ClientAddress, ClientEmail, Contact_PhoneNumber, Description, Date_Aquired, Date_UnAquired, isDeleted) values ('Voomm', '593 Northwestern Center', 'irowcliffe0@163.com', '(616) 3468490', 'Business Development', '2021-12-05', '2023-07-21', 0);
insert into Clients (ClientName, ClientAddress, ClientEmail, Contact_PhoneNumber, Description, Date_Aquired, Date_UnAquired, isDeleted) values ('Riffpath', '63 Laurel Hill', 'amuschette1@phoca.cz', '(321) 5556778', 'Support', '2022-03-21', '2022-07-23', 0);
insert into Clients (ClientName, ClientAddress, ClientEmail, Contact_PhoneNumber, Description, Date_Aquired, Date_UnAquired, isDeleted) values ('Topiclounge', '68 Bartillon Plaza', 'ahabergham2@biblegateway.com', '(818) 6726189', 'Human Resources', '2023-12-13', '2022-02-22', 0);
insert into Clients (ClientName, ClientAddress, ClientEmail, Contact_PhoneNumber, Description, Date_Aquired, Date_UnAquired, isDeleted) values ('Jazzy', '06202 Jackson Park', 'cmaryott3@paginegialle.it', '(374) 1842143', 'Services', '2022-08-17', '2023-08-27', 0);
insert into Clients (ClientName, ClientAddress, ClientEmail, Contact_PhoneNumber, Description, Date_Aquired, Date_UnAquired, isDeleted) values ('Mynte', '758 Vera Circle', 'wcleiment4@nps.gov', '(260) 7142834', 'Sales', '2022-05-12', '2022-10-10', 1);
insert into Clients (ClientName, ClientAddress, ClientEmail, Contact_PhoneNumber, Description, Date_Aquired, Date_UnAquired, isDeleted) values ('Bubbletube', '27 Luster Pass', 'mtuvey5@woothemes.com', '(454) 6738502', 'Research and Development', '2022-01-19', '2022-04-05', 0);
insert into Clients (ClientName, ClientAddress, ClientEmail, Contact_PhoneNumber, Description, Date_Aquired, Date_UnAquired, isDeleted) values ('Zoombeat', '49164 Hanover Crossing', 'dfragino6@nature.com', '(858) 3359951', 'Training', '2022-01-28', '2023-01-01', 1);
insert into Clients (ClientName, ClientAddress, ClientEmail, Contact_PhoneNumber, Description, Date_Aquired, Date_UnAquired, isDeleted) values ('Twinder', '4 Steensland Park', 'cbarczynski7@ihg.com', '(954) 8296344', 'Marketing', '2021-12-09', '2023-11-23', 0);
insert into Clients (ClientName, ClientAddress, ClientEmail, Contact_PhoneNumber, Description, Date_Aquired, Date_UnAquired, isDeleted) values ('Eadel', '68 3rd Place', 'vreubens8@wiley.com', '(219) 5689448', 'Legal', '2022-12-28', '2023-08-16', 1);
insert into Clients (ClientName, ClientAddress, ClientEmail, Contact_PhoneNumber, Description, Date_Aquired, Date_UnAquired, isDeleted) values ('Meemm', '17729 Basil Way', 'mmulvey9@google.fr', '(298) 8352465', 'Accounting', '2021-12-14', '2022-04-05', 0);
insert into Clients (ClientName, ClientAddress, ClientEmail, Contact_PhoneNumber, Description, Date_Aquired, Date_UnAquired, isDeleted) values ('Wikibox', '5 Stoughton Pass', 'itillmana@t.co', '(225) 2590996', 'Legal', '2023-02-23', '2021-12-15', 0);
insert into Clients (ClientName, ClientAddress, ClientEmail, Contact_PhoneNumber, Description, Date_Aquired, Date_UnAquired, isDeleted) values ('Brightbean', '7039 Grim Junction', 'rbrackenburyb@ibm.com', '(688) 5226696', 'Product Management', '2022-06-17', '2022-04-09', 0);
insert into Clients (ClientName, ClientAddress, ClientEmail, Contact_PhoneNumber, Description, Date_Aquired, Date_UnAquired, isDeleted) values ('Yamia', '5368 Grayhawk Road', 'spartlettc@dailymail.co.uk', '(783) 4340767', 'Legal', '2022-02-12', '2022-12-16', 0);
insert into Clients (ClientName, ClientAddress, ClientEmail, Contact_PhoneNumber, Description, Date_Aquired, Date_UnAquired, isDeleted) values ('Wikido', '88 Cardinal Avenue', 'mclendinningd@networkadvertising.org', '(169) 8139770', 'Marketing', '2022-09-07', '2023-01-19', 1);
insert into Clients (ClientName, ClientAddress, ClientEmail, Contact_PhoneNumber, Description, Date_Aquired, Date_UnAquired, isDeleted) values ('Zoombeat', '5478 Buell Park', 'vlefleye@unicef.org', '(990) 6010857', 'Product Management', '2023-02-20', '2023-01-08', 0);
insert into Clients (ClientName, ClientAddress, ClientEmail, Contact_PhoneNumber, Description, Date_Aquired, Date_UnAquired, isDeleted) values ('Jamia', '25 Huxley Road', 'schidlowf@ed.gov', '(204) 5569059', 'Engineering', '2022-11-08', '2022-03-25', 1);
insert into Clients (ClientName, ClientAddress, ClientEmail, Contact_PhoneNumber, Description, Date_Aquired, Date_UnAquired, isDeleted) values ('Gigaclub', '77 New Castle Point', 'whairsg@wikispaces.com', '(174) 2174103', 'Product Management', '2023-02-27', '2022-06-13', 1);
insert into Clients (ClientName, ClientAddress, ClientEmail, Contact_PhoneNumber, Description, Date_Aquired, Date_UnAquired, isDeleted) values ('Shufflester', '7 Gale Alley', 'ajusticeh@earthlink.net', '(616) 2675249', 'Sales', '2023-10-23', '2024-01-22', 1);
insert into Clients (ClientName, ClientAddress, ClientEmail, Contact_PhoneNumber, Description, Date_Aquired, Date_UnAquired, isDeleted) values ('Yodo', '83 Stuart Park', 'brouzeti@squidoo.com', '(806) 8071401', 'Accounting', '2023-01-12', '2023-11-26', 1);
insert into Clients (ClientName, ClientAddress, ClientEmail, Contact_PhoneNumber, Description, Date_Aquired, Date_UnAquired, isDeleted) values ('Plambee', '78 Barnett Hill', 'kinglesj@360.cn', '(869) 1359584', 'Business Development', '2022-06-06', '2023-09-11', 1);

insert into Positions (Description, BaseRate, isDeleted) values ('Training', 9899, 0);
insert into Positions (Description, BaseRate, isDeleted) values ('Business Development', 2896, 1);
insert into Positions (Description, BaseRate, isDeleted) values ('Human Resources', 2553, 0);
insert into Positions (Description, BaseRate, isDeleted) values ('Support', 3822, 0);
insert into Positions (Description, BaseRate, isDeleted) values ('Product Management', 4538, 0);
insert into Positions (Description, BaseRate, isDeleted) values ('Support', 4690, 1);
insert into Positions (Description, BaseRate, isDeleted) values ('Research and Development', 9295, 1);
insert into Positions (Description, BaseRate, isDeleted) values ('Business Development', 8130, 0);
insert into Positions (Description, BaseRate, isDeleted) values ('Training', 4057, 0);
insert into Positions (Description, BaseRate, isDeleted) values ('Support', 3768, 0);
insert into Positions (Description, BaseRate, isDeleted) values ('Research and Development', 2984, 0);
insert into Positions (Description, BaseRate, isDeleted) values ('Support', 5683, 1);
insert into Positions (Description, BaseRate, isDeleted) values ('Engineering', 8672, 1);
insert into Positions (Description, BaseRate, isDeleted) values ('Business Development', 1154, 0);
insert into Positions (Description, BaseRate, isDeleted) values ('Research and Development', 6376, 0);
insert into Positions (Description, BaseRate, isDeleted) values ('Training', 8924, 1);
insert into Positions (Description, BaseRate, isDeleted) values ('Marketing', 7993, 1);
insert into Positions (Description, BaseRate, isDeleted) values ('Research and Development', 7751, 1);
insert into Positions (Description, BaseRate, isDeleted) values ('Accounting', 5379, 1);
insert into Positions (Description, BaseRate, isDeleted) values ('Business Development', 5232, 0);

insert into HAEmployees (Employee_FirstName, Employee_LastName, PositionID, Employee_Email, Employee_PhoneNumber, isDeleted) values ('Sloane', 'Crutcher', 5, 'scrutcher0@ox.ac.uk', '(787) 7068257', 1);
insert into HAEmployees (Employee_FirstName, Employee_LastName, PositionID, Employee_Email, Employee_PhoneNumber, isDeleted) values ('Katheryn', 'Jurewicz', 7, 'kjurewicz1@reference.com', '(841) 7496880', 0);
insert into HAEmployees (Employee_FirstName, Employee_LastName, PositionID, Employee_Email, Employee_PhoneNumber, isDeleted) values ('Cullen', 'Gatecliff', 18, 'cgatecliff2@unblog.fr', '(579) 4413041', 1);
insert into HAEmployees (Employee_FirstName, Employee_LastName, PositionID, Employee_Email, Employee_PhoneNumber, isDeleted) values ('Willow', 'Bellord', 6, 'wbellord3@skype.com', '(520) 2609064', 1);
insert into HAEmployees (Employee_FirstName, Employee_LastName, PositionID, Employee_Email, Employee_PhoneNumber, isDeleted) values ('Aubree', 'Shakespear', 15, 'ashakespear4@economist.com', '(155) 1939926', 1);
insert into HAEmployees (Employee_FirstName, Employee_LastName, PositionID, Employee_Email, Employee_PhoneNumber, isDeleted) values ('Karlen', 'Tilt', 11, 'ktilt5@state.tx.us', '(749) 9897848', 0);
insert into HAEmployees (Employee_FirstName, Employee_LastName, PositionID, Employee_Email, Employee_PhoneNumber, isDeleted) values ('Cati', 'Stannas', 7, 'cstannas6@wikia.com', '(283) 7545640', 0);
insert into HAEmployees (Employee_FirstName, Employee_LastName, PositionID, Employee_Email, Employee_PhoneNumber, isDeleted) values ('Cathryn', 'Arderne', 17, 'carderne7@wikispaces.com', '(780) 4986127', 1);
insert into HAEmployees (Employee_FirstName, Employee_LastName, PositionID, Employee_Email, Employee_PhoneNumber, isDeleted) values ('Constancy', 'Ockwell', 1, 'cockwell8@oakley.com', '(310) 7466959', 0);
insert into HAEmployees (Employee_FirstName, Employee_LastName, PositionID, Employee_Email, Employee_PhoneNumber, isDeleted) values ('Town', 'Hurle', 2, 'thurle9@businessweek.com', '(445) 2994563', 0);
insert into HAEmployees (Employee_FirstName, Employee_LastName, PositionID, Employee_Email, Employee_PhoneNumber, isDeleted) values ('Dalia', 'Guilleton', 12, 'dguilletona@tiny.cc', '(103) 8453305', 0);
insert into HAEmployees (Employee_FirstName, Employee_LastName, PositionID, Employee_Email, Employee_PhoneNumber, isDeleted) values ('Cori', 'O''Fearguise', 8, 'cofearguiseb@noaa.gov', '(444) 3822723', 1);
insert into HAEmployees (Employee_FirstName, Employee_LastName, PositionID, Employee_Email, Employee_PhoneNumber, isDeleted) values ('Wilburt', 'Beeck', 16, 'wbeeckc@businessweek.com', '(535) 7598100', 0);
insert into HAEmployees (Employee_FirstName, Employee_LastName, PositionID, Employee_Email, Employee_PhoneNumber, isDeleted) values ('Melany', 'Gerrels', 2, 'mgerrelsd@latimes.com', '(200) 2912753', 1);
insert into HAEmployees (Employee_FirstName, Employee_LastName, PositionID, Employee_Email, Employee_PhoneNumber, isDeleted) values ('Cirstoforo', 'Castanos', 20, 'ccastanose@noaa.gov', '(273) 1731331', 0);
insert into HAEmployees (Employee_FirstName, Employee_LastName, PositionID, Employee_Email, Employee_PhoneNumber, isDeleted) values ('Frederico', 'Pamphilon', 6, 'fpamphilonf@squidoo.com', '(642) 6508434', 0);
insert into HAEmployees (Employee_FirstName, Employee_LastName, PositionID, Employee_Email, Employee_PhoneNumber, isDeleted) values ('Pamelina', 'McEvon', 1, 'pmcevong@biglobe.ne.jp', '(116) 4709270', 0);
insert into HAEmployees (Employee_FirstName, Employee_LastName, PositionID, Employee_Email, Employee_PhoneNumber, isDeleted) values ('Maribel', 'Fiennes', 14, 'mfiennesh@slideshare.net', '(963) 8339288', 1);
insert into HAEmployees (Employee_FirstName, Employee_LastName, PositionID, Employee_Email, Employee_PhoneNumber, isDeleted) values ('Kalindi', 'Mynard', 6, 'kmynardi@go.com', '(680) 2024700', 0);
insert into HAEmployees (Employee_FirstName, Employee_LastName, PositionID, Employee_Email, Employee_PhoneNumber, isDeleted) values ('Leonid', 'Roxbrough', 9, 'lroxbroughj@bloomberg.com', '(305) 5262984', 1);

insert into Users (Username, Password, FirstName, LastName, userType, HAEmployeeID, isDeleted) values ('sbuckler0', 'NRO0YT77Q5uT', 'Skyler', 'Buckler', 'Koala', 3, 1);
insert into Users (Username, Password, FirstName, LastName, userType, HAEmployeeID, isDeleted) values ('gleyninye1', 'mo9l8jkHLK', 'Granthem', 'Leyninye', 'Dragon, frilled', 8, 1);
insert into Users (Username, Password, FirstName, LastName, userType, HAEmployeeID, isDeleted) values ('pgilffillan2', 'T6OoQUg12FGK', 'Phillida', 'Gilffillan', 'Small-clawed otter', 1, 0);
insert into Users (Username, Password, FirstName, LastName, userType, HAEmployeeID, isDeleted) values ('wgreedy3', 'hHml44vk', 'Wren', 'Greedy', 'Roe deer', 8, 0);
insert into Users (Username, Password, FirstName, LastName, userType, HAEmployeeID, isDeleted) values ('cvinden4', 'f6QVXaS', 'Curr', 'Vinden', 'Eagle, long-crested hawk', 16, 0);
insert into Users (Username, Password, FirstName, LastName, userType, HAEmployeeID, isDeleted) values ('dportam5', 'a6v0DAl1jv9V', 'Dodi', 'Portam', 'American Virginia opossum', 10, 1);
insert into Users (Username, Password, FirstName, LastName, userType, HAEmployeeID, isDeleted) values ('lgrinnov6', 'MF9hwHUJ', 'Lyn', 'Grinnov', 'Penguin, fairy', 12, 0);
insert into Users (Username, Password, FirstName, LastName, userType, HAEmployeeID, isDeleted) values ('rkime7', 'OUmfF9NuIhgq', 'Robbi', 'Kime', 'Cape clawless otter', 4, 0);
insert into Users (Username, Password, FirstName, LastName, userType, HAEmployeeID, isDeleted) values ('jparnell8', 'a1jtGpXaD', 'Jyoti', 'Parnell', 'Sparrow, house', 5, 0);
insert into Users (Username, Password, FirstName, LastName, userType, HAEmployeeID, isDeleted) values ('olowdwell9', 'aO4MjwZ', 'Olia', 'Lowdwell', 'Frilled dragon', 15, 0);
insert into Users (Username, Password, FirstName, LastName, userType, HAEmployeeID, isDeleted) values ('mcrasforda', 'rxTviLK', 'Marina', 'Crasford', 'Goanna lizard', 1, 1);
insert into Users (Username, Password, FirstName, LastName, userType, HAEmployeeID, isDeleted) values ('gcattob', 'nDFkIPWT33', 'Gloriane', 'Catto', 'Wagtail, african pied', 7, 1);
insert into Users (Username, Password, FirstName, LastName, userType, HAEmployeeID, isDeleted) values ('kflockhartc', 'bDa3A7', 'Kingston', 'Flockhart', 'Chameleon (unidentified)', 19, 0);
insert into Users (Username, Password, FirstName, LastName, userType, HAEmployeeID, isDeleted) values ('mcouroyd', 'bA9JHH2xpwDr', 'Maryrose', 'Couroy', 'Swan, trumpeter', 2, 0);
insert into Users (Username, Password, FirstName, LastName, userType, HAEmployeeID, isDeleted) values ('pquinceye', 'Iow9D9HLmCcv', 'Penni', 'Quincey', 'Mynah, indian', 2, 0);
insert into Users (Username, Password, FirstName, LastName, userType, HAEmployeeID, isDeleted) values ('mduffieldf', 'kwGxueHdy', 'Monique', 'Duffield', 'Cattle egret', 3, 1);
insert into Users (Username, Password, FirstName, LastName, userType, HAEmployeeID, isDeleted) values ('dsaggg', 'Dte8Ft1NOa', 'Darryl', 'Sagg', 'Heron, green-backed', 20, 0);
insert into Users (Username, Password, FirstName, LastName, userType, HAEmployeeID, isDeleted) values ('npibsworthh', 'trJsLz', 'Nadya', 'Pibsworth', 'Deer, mule', 2, 0);
insert into Users (Username, Password, FirstName, LastName, userType, HAEmployeeID, isDeleted) values ('nwolferi', 'mIIHjtD0c', 'Nerissa', 'Wolfer', 'Blue duck', 13, 0);
insert into Users (Username, Password, FirstName, LastName, userType, HAEmployeeID, isDeleted) values ('ldefondj', 'o6sreFBlA', 'Linda', 'Defond', 'Jaguar', 6, 1);

insert into AssignedEmployees (HAEmployeeID, ClientID, PreviousAssignment, DateAssigned, isDeleted) values (15, 15, 9, '2022-07-22', 0);
insert into AssignedEmployees (HAEmployeeID, ClientID, PreviousAssignment, DateAssigned, isDeleted) values (7, 11, 1, '2022-06-17', 0);
insert into AssignedEmployees (HAEmployeeID, ClientID, PreviousAssignment, DateAssigned, isDeleted) values (15, 1, 8, '2022-02-16', 0);
insert into AssignedEmployees (HAEmployeeID, ClientID, PreviousAssignment, DateAssigned, isDeleted) values (19, 17, 16, '2022-08-03', 0);
insert into AssignedEmployees (HAEmployeeID, ClientID, PreviousAssignment, DateAssigned, isDeleted) values (18, 6, 19, '2022-10-30', 1);
insert into AssignedEmployees (HAEmployeeID, ClientID, PreviousAssignment, DateAssigned, isDeleted) values (16, 15, 15, '2022-10-05', 0);
insert into AssignedEmployees (HAEmployeeID, ClientID, PreviousAssignment, DateAssigned, isDeleted) values (20, 10, 11, '2022-04-11', 1);
insert into AssignedEmployees (HAEmployeeID, ClientID, PreviousAssignment, DateAssigned, isDeleted) values (17, 2, 3, '2021-12-12', 1);
insert into AssignedEmployees (HAEmployeeID, ClientID, PreviousAssignment, DateAssigned, isDeleted) values (16, 3, 2, '2022-05-23', 0);
insert into AssignedEmployees (HAEmployeeID, ClientID, PreviousAssignment, DateAssigned, isDeleted) values (20, 6, 13, '2022-05-07', 1);
insert into AssignedEmployees (HAEmployeeID, ClientID, PreviousAssignment, DateAssigned, isDeleted) values (3, 5, 2, '2022-09-30', 0);
insert into AssignedEmployees (HAEmployeeID, ClientID, PreviousAssignment, DateAssigned, isDeleted) values (8, 20, 4, '2022-08-02', 1);
insert into AssignedEmployees (HAEmployeeID, ClientID, PreviousAssignment, DateAssigned, isDeleted) values (18, 15, 5, '2022-05-27', 1);
insert into AssignedEmployees (HAEmployeeID, ClientID, PreviousAssignment, DateAssigned, isDeleted) values (18, 1, 13, '2022-07-31', 0);
insert into AssignedEmployees (HAEmployeeID, ClientID, PreviousAssignment, DateAssigned, isDeleted) values (1, 16, 17, '2022-01-02', 0);
insert into AssignedEmployees (HAEmployeeID, ClientID, PreviousAssignment, DateAssigned, isDeleted) values (12, 10, 19, '2022-07-14', 1);
insert into AssignedEmployees (HAEmployeeID, ClientID, PreviousAssignment, DateAssigned, isDeleted) values (13, 12, 1, '2022-01-02', 1);
insert into AssignedEmployees (HAEmployeeID, ClientID, PreviousAssignment, DateAssigned, isDeleted) values (6, 12, 6, '2022-03-09', 0);
insert into AssignedEmployees (HAEmployeeID, ClientID, PreviousAssignment, DateAssigned, isDeleted) values (2, 5, 10, '2022-08-30', 0);
insert into AssignedEmployees (HAEmployeeID, ClientID, PreviousAssignment, DateAssigned, isDeleted) values (10, 9, 9, '2022-07-23', 0);

insert into Banks (BankName, Bank_PhoneNumber, isDeleted) values ('Oyondu', '(729) 5468657', 0);
insert into Banks (BankName, Bank_PhoneNumber, isDeleted) values ('Devpulse', '(571) 5604829', 0);
insert into Banks (BankName, Bank_PhoneNumber, isDeleted) values ('Eazzy', '(796) 2372905', 1);
insert into Banks (BankName, Bank_PhoneNumber, isDeleted) values ('Eabox', '(149) 6584139', 1);
insert into Banks (BankName, Bank_PhoneNumber, isDeleted) values ('Mita', '(798) 4639489', 1);
insert into Banks (BankName, Bank_PhoneNumber, isDeleted) values ('Feedbug', '(576) 4635282', 1);
insert into Banks (BankName, Bank_PhoneNumber, isDeleted) values ('Trudoo', '(474) 1741112', 1);
insert into Banks (BankName, Bank_PhoneNumber, isDeleted) values ('Fivebridge', '(368) 2104547', 1);
insert into Banks (BankName, Bank_PhoneNumber, isDeleted) values ('Divape', '(875) 3387264', 1);
insert into Banks (BankName, Bank_PhoneNumber, isDeleted) values ('Skinder', '(130) 4083459', 1);
insert into Banks (BankName, Bank_PhoneNumber, isDeleted) values ('Gabspot', '(567) 9928410', 1);
insert into Banks (BankName, Bank_PhoneNumber, isDeleted) values ('Linklinks', '(491) 8500114', 0);
insert into Banks (BankName, Bank_PhoneNumber, isDeleted) values ('Trupe', '(193) 4720211', 1);
insert into Banks (BankName, Bank_PhoneNumber, isDeleted) values ('Skinte', '(640) 4169491', 1);
insert into Banks (BankName, Bank_PhoneNumber, isDeleted) values ('Yozio', '(179) 4459337', 1);
insert into Banks (BankName, Bank_PhoneNumber, isDeleted) values ('Tagchat', '(556) 2668803', 0);
insert into Banks (BankName, Bank_PhoneNumber, isDeleted) values ('Edgeblab', '(699) 1302927', 1);
insert into Banks (BankName, Bank_PhoneNumber, isDeleted) values ('Realfire', '(746) 6743949', 0);
insert into Banks (BankName, Bank_PhoneNumber, isDeleted) values ('Quamba', '(987) 9225139', 0);
insert into Banks (BankName, Bank_PhoneNumber, isDeleted) values ('Trilith', '(142) 6380620', 1);

insert into BankAccounts (ClientID, BankID, AccountType, AccountNumber, isDeleted) values (1, 19, 'Bigtax', 1292567986, 1);
insert into BankAccounts (ClientID, BankID, AccountType, AccountNumber, isDeleted) values (4, 5, 'Bitwolf', 8796444603, 0);
insert into BankAccounts (ClientID, BankID, AccountType, AccountNumber, isDeleted) values (12, 10, 'Konklab', 6607571131, 0);
insert into BankAccounts (ClientID, BankID, AccountType, AccountNumber, isDeleted) values (14, 2, 'Veribet', 8319684092, 0);
insert into BankAccounts (ClientID, BankID, AccountType, AccountNumber, isDeleted) values (10, 17, 'Solarbreeze', 7720873749, 1);
insert into BankAccounts (ClientID, BankID, AccountType, AccountNumber, isDeleted) values (4, 4, 'Trippledex', 4201956517, 0);
insert into BankAccounts (ClientID, BankID, AccountType, AccountNumber, isDeleted) values (13, 6, 'It', 8185333878, 1);
insert into BankAccounts (ClientID, BankID, AccountType, AccountNumber, isDeleted) values (19, 16, 'Home Ing', 2517392443, 1);
insert into BankAccounts (ClientID, BankID, AccountType, AccountNumber, isDeleted) values (5, 3, 'Span', 4399468217, 0);
insert into BankAccounts (ClientID, BankID, AccountType, AccountNumber, isDeleted) values (5, 6, 'Opela', 2423841853, 0);
insert into BankAccounts (ClientID, BankID, AccountType, AccountNumber, isDeleted) values (17, 19, 'Stringtough', 6199853420, 1);
insert into BankAccounts (ClientID, BankID, AccountType, AccountNumber, isDeleted) values (11, 9, 'Latlux', 9795431293, 0);
insert into BankAccounts (ClientID, BankID, AccountType, AccountNumber, isDeleted) values (8, 18, 'Fintone', 1345049227, 1);
insert into BankAccounts (ClientID, BankID, AccountType, AccountNumber, isDeleted) values (19, 13, 'Mat Lam Tam', 8214688799, 1);
insert into BankAccounts (ClientID, BankID, AccountType, AccountNumber, isDeleted) values (18, 12, 'Overhold', 8875850926, 1);
insert into BankAccounts (ClientID, BankID, AccountType, AccountNumber, isDeleted) values (12, 11, 'Latlux', 2624785575, 1);
insert into BankAccounts (ClientID, BankID, AccountType, AccountNumber, isDeleted) values (5, 10, 'Home Ing', 9354846491, 0);
insert into BankAccounts (ClientID, BankID, AccountType, AccountNumber, isDeleted) values (10, 20, 'Aerified', 2216792099, 0);
insert into BankAccounts (ClientID, BankID, AccountType, AccountNumber, isDeleted) values (9, 11, 'Fintone', 1073412950, 0);
insert into BankAccounts (ClientID, BankID, AccountType, AccountNumber, isDeleted) values (3, 12, 'Alphazap', 7469363052, 1);

insert into TransactionTypes (Description, isCredit, isDeleted) values ('Crimson', 0, 1);
insert into TransactionTypes (Description, isCredit, isDeleted) values ('Green', 1, 1);
insert into TransactionTypes (Description, isCredit, isDeleted) values ('Puce', 1, 1);
insert into TransactionTypes (Description, isCredit, isDeleted) values ('Orange', 0, 0);
insert into TransactionTypes (Description, isCredit, isDeleted) values ('Orange', 1, 0);
insert into TransactionTypes (Description, isCredit, isDeleted) values ('Purple', 0, 1);
insert into TransactionTypes (Description, isCredit, isDeleted) values ('Maroon', 0, 1);
insert into TransactionTypes (Description, isCredit, isDeleted) values ('Pink', 0, 0);
insert into TransactionTypes (Description, isCredit, isDeleted) values ('Indigo', 0, 1);
insert into TransactionTypes (Description, isCredit, isDeleted) values ('Goldenrod', 0, 1);
insert into TransactionTypes (Description, isCredit, isDeleted) values ('Crimson', 1, 1);
insert into TransactionTypes (Description, isCredit, isDeleted) values ('Puce', 0, 0);
insert into TransactionTypes (Description, isCredit, isDeleted) values ('Green', 1, 0);
insert into TransactionTypes (Description, isCredit, isDeleted) values ('Puce', 1, 1);
insert into TransactionTypes (Description, isCredit, isDeleted) values ('Fuscia', 1, 0);
insert into TransactionTypes (Description, isCredit, isDeleted) values ('Red', 0, 1);
insert into TransactionTypes (Description, isCredit, isDeleted) values ('Khaki', 1, 1);
insert into TransactionTypes (Description, isCredit, isDeleted) values ('Blue', 0, 0);
insert into TransactionTypes (Description, isCredit, isDeleted) values ('Yellow', 0, 0);
insert into TransactionTypes (Description, isCredit, isDeleted) values ('Purple', 1, 1);

insert into Transactions (BankAccountID, Date_Made, Date_Processed, Amount, Description, TransactionTypeID, isDeleted) values (3, '2022-07-24', '2022-10-07', 71130.52, 'Automotive', 7, 0);
insert into Transactions (BankAccountID, Date_Made, Date_Processed, Amount, Description, TransactionTypeID, isDeleted) values (16, '2022-01-19', '2022-07-28', 55800.4, 'Beauty', 1, 0);
insert into Transactions (BankAccountID, Date_Made, Date_Processed, Amount, Description, TransactionTypeID, isDeleted) values (13, '2021-12-12', '2022-08-21', 29089.92, 'Automotive', 11, 1);
insert into Transactions (BankAccountID, Date_Made, Date_Processed, Amount, Description, TransactionTypeID, isDeleted) values (10, '2022-05-09', '2022-11-05', 75680.62, 'Baby', 14, 1);
insert into Transactions (BankAccountID, Date_Made, Date_Processed, Amount, Description, TransactionTypeID, isDeleted) values (4, '2022-05-29', '2022-05-18', 76365.57, 'Music', 2, 0);
insert into Transactions (BankAccountID, Date_Made, Date_Processed, Amount, Description, TransactionTypeID, isDeleted) values (5, '2022-01-10', '2022-05-03', 97926.76, 'Jewelry', 7, 0);
insert into Transactions (BankAccountID, Date_Made, Date_Processed, Amount, Description, TransactionTypeID, isDeleted) values (8, '2022-03-03', '2022-10-17', 81177.69, 'Electronics', 5, 0);
insert into Transactions (BankAccountID, Date_Made, Date_Processed, Amount, Description, TransactionTypeID, isDeleted) values (19, '2022-03-07', '2022-10-31', 53587.03, 'Movies', 2, 1);
insert into Transactions (BankAccountID, Date_Made, Date_Processed, Amount, Description, TransactionTypeID, isDeleted) values (10, '2022-02-15', '2022-07-23', 74957.8, 'Clothing', 12, 1);
insert into Transactions (BankAccountID, Date_Made, Date_Processed, Amount, Description, TransactionTypeID, isDeleted) values (1, '2022-10-20', '2022-03-21', 10601.13, 'Outdoors', 13, 1);
insert into Transactions (BankAccountID, Date_Made, Date_Processed, Amount, Description, TransactionTypeID, isDeleted) values (16, '2022-04-05', '2021-12-26', 45201.71, 'Books', 2, 0);
insert into Transactions (BankAccountID, Date_Made, Date_Processed, Amount, Description, TransactionTypeID, isDeleted) values (6, '2022-02-04', '2022-02-02', 70497.89, 'Jewelry', 5, 1);
insert into Transactions (BankAccountID, Date_Made, Date_Processed, Amount, Description, TransactionTypeID, isDeleted) values (4, '2022-10-07', '2022-01-19', 49606.29, 'Beauty', 11, 0);
insert into Transactions (BankAccountID, Date_Made, Date_Processed, Amount, Description, TransactionTypeID, isDeleted) values (5, '2022-04-27', '2022-02-22', 28582.82, 'Industrial', 2, 1);
insert into Transactions (BankAccountID, Date_Made, Date_Processed, Amount, Description, TransactionTypeID, isDeleted) values (16, '2022-09-23', '2021-12-07', 38565.56, 'Automotive', 19, 0);
insert into Transactions (BankAccountID, Date_Made, Date_Processed, Amount, Description, TransactionTypeID, isDeleted) values (12, '2022-02-14', '2022-05-13', 53937.08, 'Computers', 11, 1);
insert into Transactions (BankAccountID, Date_Made, Date_Processed, Amount, Description, TransactionTypeID, isDeleted) values (14, '2022-10-15', '2021-12-03', 1461.32, 'Music', 15, 0);
insert into Transactions (BankAccountID, Date_Made, Date_Processed, Amount, Description, TransactionTypeID, isDeleted) values (9, '2022-03-11', '2022-11-01', 39831.2, 'Music', 18, 1);
insert into Transactions (BankAccountID, Date_Made, Date_Processed, Amount, Description, TransactionTypeID, isDeleted) values (18, '2022-04-08', '2022-02-13', 46548.77, 'Grocery', 8, 1);
insert into Transactions (BankAccountID, Date_Made, Date_Processed, Amount, Description, TransactionTypeID, isDeleted) values (3, '2021-11-24', '2022-06-07', 28792.5, 'Toys', 1, 1);

insert into AccountTypes (AccountTypeName, Description, isMain, isDeleted) values ('Glass', 'Electrician', 1, 1);
insert into AccountTypes (AccountTypeName, Description, isMain, isDeleted) values ('Granite', 'Equipment Operator', 0, 0);
insert into AccountTypes (AccountTypeName, Description, isMain, isDeleted) values ('Glass', 'Millwright', 0, 0);
insert into AccountTypes (AccountTypeName, Description, isMain, isDeleted) values ('Plexiglass', 'Sheet Metal Worker', 0, 1);
insert into AccountTypes (AccountTypeName, Description, isMain, isDeleted) values ('Glass', 'Plasterers', 1, 1);
insert into AccountTypes (AccountTypeName, Description, isMain, isDeleted) values ('Wood', 'Boilermaker', 0, 0);
insert into AccountTypes (AccountTypeName, Description, isMain, isDeleted) values ('Plastic', 'Plumber', 1, 0);
insert into AccountTypes (AccountTypeName, Description, isMain, isDeleted) values ('Rubber', 'Refridgeration', 0, 1);
insert into AccountTypes (AccountTypeName, Description, isMain, isDeleted) values ('Brass', 'Carpenter', 0, 0);
insert into AccountTypes (AccountTypeName, Description, isMain, isDeleted) values ('Brass', 'Tile Setter', 0, 0);
insert into AccountTypes (AccountTypeName, Description, isMain, isDeleted) values ('Plexiglass', 'Welder', 0, 1);
insert into AccountTypes (AccountTypeName, Description, isMain, isDeleted) values ('Vinyl', 'Pipelayer', 0, 0);
insert into AccountTypes (AccountTypeName, Description, isMain, isDeleted) values ('Stone', 'Sheet Metal Worker', 1, 1);
insert into AccountTypes (AccountTypeName, Description, isMain, isDeleted) values ('Granite', 'Laborer', 1, 0);
insert into AccountTypes (AccountTypeName, Description, isMain, isDeleted) values ('Granite', 'HVAC', 1, 0);
insert into AccountTypes (AccountTypeName, Description, isMain, isDeleted) values ('Stone', 'Pipefitter', 0, 0);
insert into AccountTypes (AccountTypeName, Description, isMain, isDeleted) values ('Rubber', 'Terrazzo', 0, 1);
insert into AccountTypes (AccountTypeName, Description, isMain, isDeleted) values ('Wood', 'Millwright', 1, 1);
insert into AccountTypes (AccountTypeName, Description, isMain, isDeleted) values ('Glass', 'Sheet Metal Worker', 1, 0);
insert into AccountTypes (AccountTypeName, Description, isMain, isDeleted) values ('Granite', 'Terrazzo', 1, 0);

insert into Accounts (AccountTypeID, TransactionID, isDeleted) values (2.74, 16, 1);
insert into Accounts (AccountTypeID, TransactionID, isDeleted) values (3.57, 4, 1);
insert into Accounts (AccountTypeID, TransactionID, isDeleted) values (14.95, 16, 1);
insert into Accounts (AccountTypeID, TransactionID, isDeleted) values (17.66, 6, 0);
insert into Accounts (AccountTypeID, TransactionID, isDeleted) values (10.75, 19, 0);
insert into Accounts (AccountTypeID, TransactionID, isDeleted) values (12.26, 12, 0);
insert into Accounts (AccountTypeID, TransactionID, isDeleted) values (14.97, 1, 1);
insert into Accounts (AccountTypeID, TransactionID, isDeleted) values (5.09, 14, 0);
insert into Accounts (AccountTypeID, TransactionID, isDeleted) values (16.81, 18, 1);
insert into Accounts (AccountTypeID, TransactionID, isDeleted) values (14.08, 19, 1);
insert into Accounts (AccountTypeID, TransactionID, isDeleted) values (2.78, 17, 0);
insert into Accounts (AccountTypeID, TransactionID, isDeleted) values (13.71, 17, 1);
insert into Accounts (AccountTypeID, TransactionID, isDeleted) values (12.16, 11, 1);
insert into Accounts (AccountTypeID, TransactionID, isDeleted) values (15.7, 19, 1);
insert into Accounts (AccountTypeID, TransactionID, isDeleted) values (4.04, 1, 0);
insert into Accounts (AccountTypeID, TransactionID, isDeleted) values (1.63, 8, 0);
insert into Accounts (AccountTypeID, TransactionID, isDeleted) values (12.89, 9, 1);
insert into Accounts (AccountTypeID, TransactionID, isDeleted) values (7.61, 3, 0);
insert into Accounts (AccountTypeID, TransactionID, isDeleted) values (13.45, 4, 1);
insert into Accounts (AccountTypeID, TransactionID, isDeleted) values (13.66, 4, 0);